In [1]:
import numpy as np

# TASK1

In [2]:
Data1 = np.genfromtxt("DS1_C4_S1_Employee_Data_Challenge.csv",delimiter=',',skip_header=1)
print('The average of employee age is',np.mean(Data1))

The average of employee age is 26.88


In [3]:
Data1[:,1]

array([22., 27., 31., 29., 27., 26., 27., 23., 27., 32., 28., 27., 22.,
       27., 35., 33., 28., 22., 25., 27., 37., 27., 24., 27., 28., 26.,
       27., 27., 29., 49., 26., 32., 26., 24., 24., 23., 28., 28., 22.,
       26., 32., 35., 33., 31., 30., 36., 22., 23., 32., 34.])

# TASK2

In [4]:
age=Data1[:,1]
Index = np.where(age>25)
a=age[Index]
b=Index[0]
c=np.array([b,a])
print('Total number of employees above age 25 are','\n',c.T)


Total number of employees above age 25 are 
 [[ 1. 27.]
 [ 2. 31.]
 [ 3. 29.]
 [ 4. 27.]
 [ 5. 26.]
 [ 6. 27.]
 [ 8. 27.]
 [ 9. 32.]
 [10. 28.]
 [11. 27.]
 [13. 27.]
 [14. 35.]
 [15. 33.]
 [16. 28.]
 [19. 27.]
 [20. 37.]
 [21. 27.]
 [23. 27.]
 [24. 28.]
 [25. 26.]
 [26. 27.]
 [27. 27.]
 [28. 29.]
 [29. 49.]
 [30. 26.]
 [31. 32.]
 [32. 26.]
 [36. 28.]
 [37. 28.]
 [39. 26.]
 [40. 32.]
 [41. 35.]
 [42. 33.]
 [43. 31.]
 [44. 30.]
 [45. 36.]
 [48. 32.]
 [49. 34.]]


# TASK3

In [5]:
age=Data1[:,1]
Index = np.where((age>30)&(age<35))
a=age[Index]
b=Index[0]
c=np.array([b,a])
print('Total number of employees between age 30 and 35 are','\n',c.T)


Total number of employees between age 30 and 35 are 
 [[ 2. 31.]
 [ 9. 32.]
 [15. 33.]
 [31. 32.]
 [40. 32.]
 [42. 33.]
 [43. 31.]
 [48. 32.]
 [49. 34.]]


# Customer Retention 

# TASK1

In [6]:
Data2 = np.genfromtxt("DS1_C4_S1_Shopping_Data_Challenge.csv", delimiter=',',skip_header=1)

In [7]:
CustomerID = Data2[:,0]
Age = Data2[:,1]
Annual_Income = Data2[:,2]
Spending_Score = Data2[:,3]
Index = np.where(Spending_Score>80)[0]

arr = np.array([CustomerID[Index],Age[Index],Annual_Income[Index],Spending_Score[Index]])
arr.T


array([[  2.,  21.,  15.,  81.],
       [  8.,  23.,  18.,  94.],
       [ 12.,  35.,  19.,  99.],
       [ 20.,  35.,  23.,  98.],
       [ 26.,  29.,  28.,  82.],
       [ 30.,  23.,  29.,  87.],
       [ 34.,  18.,  33.,  92.],
       [ 36.,  21.,  33.,  81.],
       [ 42.,  24.,  38.,  92.],
       [124.,  39.,  69.,  91.],
       [128.,  40.,  71.,  95.],
       [136.,  29.,  73.,  88.],
       [142.,  32.,  75.,  93.],
       [144.,  32.,  76.,  87.],
       [146.,  28.,  77.,  97.],
       [150.,  34.,  78.,  90.],
       [152.,  39.,  78.,  88.],
       [156.,  27.,  78.,  89.],
       [162.,  29.,  79.,  83.],
       [164.,  31.,  81.,  93.],
       [168.,  33.,  86.,  95.],
       [174.,  36.,  87.,  92.],
       [176.,  30.,  88.,  86.],
       [180.,  35.,  93.,  90.],
       [182.,  32.,  97.,  86.],
       [184.,  29.,  98.,  88.],
       [186.,  30.,  99.,  97.],
       [190.,  36., 103.,  85.],
       [194.,  38., 113.,  91.],
       [200.,  30., 137.,  83.]])

# TASK2

In [8]:
Index = np.where((Age>=20) & (Age<=24))
Data2[Index,:]

array([[[  2.,  21.,  15.,  81.],
        [  3.,  20.,  16.,   6.],
        [  4.,  23.,  16.,  77.],
        [  6.,  22.,  17.,  76.],
        [  8.,  23.,  18.,  94.],
        [ 14.,  24.,  20.,  77.],
        [ 16.,  22.,  20.,  79.],
        [ 18.,  20.,  21.,  66.],
        [ 30.,  23.,  29.,  87.],
        [ 32.,  21.,  30.,  73.],
        [ 36.,  21.,  33.,  81.],
        [ 40.,  20.,  37.,  75.],
        [ 42.,  24.,  38.,  92.],
        [ 46.,  24.,  39.,  65.],
        [ 79.,  23.,  54.,  52.],
        [ 85.,  21.,  54.,  57.],
        [ 88.,  22.,  57.,  55.],
        [ 96.,  24.,  60.,  52.],
        [100.,  20.,  61.,  49.],
        [101.,  23.,  62.,  41.],
        [106.,  21.,  62.,  42.],
        [125.,  23.,  70.,  29.],
        [135.,  20.,  73.,   5.]]])

# TASK3

In [9]:
Max_AI = max(Annual_Income)
Index = np.where(Annual_Income==Max_AI)
arr1 = np.array([CustomerID[Index],Age[Index],Annual_Income[Index],Spending_Score[Index]])


Min_AI = min(Annual_Income)
Index = np.where(Annual_Income==Min_AI)
arr2 = np.array([CustomerID[Index],Age[Index],Annual_Income[Index],Spending_Score[Index]])
print('\n', 'There are two Employee with max salaries', '\n','\n', arr1.T)
print('\n', 'There are two Employee with max salaries', '\n','\n', arr2.T)



 There are two Employee with max salaries 
 
 [[199.  32. 137.  18.]
 [200.  30. 137.  83.]]

 There are two Employee with max salaries 
 
 [[ 1. 19. 15. 39.]
 [ 2. 21. 15. 81.]]


# TASK4

In [10]:
Index = np.where((Age< 45)&(Annual_Income>=35)& (Spending_Score>75))
print('There are', np.size(Index[0]), 'customers eligible for discount')

There are 26 customers eligible for discount


# TASK5 

In [11]:
a=Data2.T
b=np.random.randint(10,50,200)
c=np.append(a,b)
d=c.reshape(5,200)
d.T

array([[  1.,  19.,  15.,  39.,  49.],
       [  2.,  21.,  15.,  81.,  36.],
       [  3.,  20.,  16.,   6.,  21.],
       [  4.,  23.,  16.,  77.,  14.],
       [  5.,  31.,  17.,  40.,  24.],
       [  6.,  22.,  17.,  76.,  28.],
       [  7.,  35.,  18.,   6.,  26.],
       [  8.,  23.,  18.,  94.,  21.],
       [  9.,  64.,  19.,   3.,  13.],
       [ 10.,  30.,  19.,  72.,  32.],
       [ 11.,  67.,  19.,  14.,  17.],
       [ 12.,  35.,  19.,  99.,  20.],
       [ 13.,  58.,  20.,  15.,  31.],
       [ 14.,  24.,  20.,  77.,  31.],
       [ 15.,  37.,  20.,  13.,  24.],
       [ 16.,  22.,  20.,  79.,  26.],
       [ 17.,  35.,  21.,  35.,  29.],
       [ 18.,  20.,  21.,  66.,  47.],
       [ 19.,  52.,  23.,  29.,  34.],
       [ 20.,  35.,  23.,  98.,  48.],
       [ 21.,  35.,  24.,  35.,  34.],
       [ 22.,  25.,  24.,  73.,  10.],
       [ 23.,  46.,  25.,   5.,  23.],
       [ 24.,  31.,  25.,  73.,  24.],
       [ 25.,  54.,  28.,  14.,  12.],
       [ 26.,  29.,  28.,

# TASK6

In [13]:
A=d[4]
B= np.where(A>45)[0]
print('Number of customer who got discount more then 45% is: ',B.size)

Number of customer who got discount more then 45% is:  21
